language: julia

os:
  - osx
  - linux

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
