name = "Multibreak"
uuid = "2db7fbaf-c681-4fb2-9fc5-9b884bdd742d"
authors = ["Gunnar Farnebäck <gunnar@lysator.liu.se>"]
version = "0.1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
